### ISSUE TITLE
imagemesher.elementsizeweightfunctions

### ISSUE THREAD

**Issue by jamesthesnake** [PetrKryslUCSD/FinEtoolsVoxelMesher.jl#2]
I ran the Labador Example problems on julia pro
 ```
ERROR: type ImageMesher has no field elementsizeweightfunctions

For lines 22-23 
	im = ImageMesher(vb, zero(eltype(vb.data)), eltype(vb.data)[100, 200])
	im.elementsizeweightfunctions = [ElementSizeWeightFunction(20.0, vec([154.0, 158.0, 98.0]), 20.0)]
```

Is this an overisght?

**Comment by jamesthesnake** [comment]
After some detective work it seems as if it's from an earlier verison of VoxelTetMeshingModule.jl, I will investigate more

**Comment by PetrKryslUCSD** [comment]
Check out the latest. The example was corrected.

**Comment by jamesthesnake** [comment]
@PetrKryslUCSD will do

**Comment by PetrKryslUCSD** [comment]
I had to push a couple more changes just now.
